package sintactico;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int P_C = 29;
  public static final int MAP = 34;
  public static final int P_A = 28;
  public static final int OP_MAYOR = 14;
  public static final int OP_NOT = 23;
  public static final int OP_AND = 21;
  public static final int TIPO_STRING = 8;
  public static final int OP_DIV = 27;
  public static final int BEGIN = 2;
  public static final int IF = 10;
  public static final int ID = 35;
  public static final int L_C = 33;
  public static final int EOF = 0;
  public static final int L_A = 32;
  public static final int ENDDECLARE = 5;
  public static final int C_C = 31;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int OP_MULT = 26;
  public static final int C_A = 30;
  public static final int OP_OR = 22;
  public static final int TIPO_INT = 6;
  public static final int DECLARE = 4;
  public static final int OP_MAYOR_IGUAL = 16;
  public static final int ELSE = 11;
  public static final int OP_SUM = 24;
  public static final int OP_IGUAL = 18;
  public static final int WHILE = 9;
  public static final int ASIGN_DECLR = 20;
  public static final int OP_MENOR_IGUAL = 15;
  public static final int CONST_STRING = 38;
  public static final int TIPO_FLOAT = 7;
  public static final int ASIGN = 19;
  public static final int END = 3;
  public static final int CONST_REAL = 37;
  public static final int OP_DIST = 17;
  public static final int PRINT = 12;
  public static final int CONST_INT = 36;
  public static final int OP_MENOR = 13;
  public static final int OP_RES = 25;
  
  /* special terminals */
  public static final int COMMENT_ERROR = 100;
  public static final int ERROR = 101;
  
  
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "DECLARE",
  "ENDDECLARE",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_STRING",
  "WHILE",
  "IF",
  "ELSE",
  "PRINT",
  "OP_MENOR",
  "OP_MAYOR",
  "OP_MENOR_IGUAL",
  "OP_MAYOR_IGUAL",
  "OP_DIST",
  "OP_IGUAL",
  "ASIGN",
  "ASIGN_DECLR",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "OP_SUM",
  "OP_RES",
  "OP_MULT",
  "OP_DIV",
  "P_A",
  "P_C",
  "C_A",
  "C_C",
  "L_A",
  "L_C",
  "MAP",
  "ID",
  "CONST_INT",
  "CONST_REAL",
  "CONST_STRING",
  "COMA"
  };
}

