package lexico;

public enum Token {
	DIGITO, LETRA, COMA, CONST_STR, CONST_REAL, CONST_INT, ID, OP_COMPARACION, OP_SUM, OP_RES, OP_MULT, OP_DIV, OP_ASIGN, OP_LOG,
	C_A, C_C, P_A, P_C, L_A, L_C, WHILE, IF, ELSE, TIPO, PRINT, DECLARE, ENDDECLARE, BEGIN, END, ERROR, ESPCHAR, COMMENT, ESPACIO, COM, MAP
}
