package lexico;

public enum Token {
	DIGITO, LETRA, COMA, CONST_STR, CONST_REAL, CONST_INT, ID, OP_AND, OP_OR, OP_NOT, OP_SUM, OP_RES, OP_MULT, OP_DIV,
	OP_MENOR, OP_MAYOR, OP_MENOR_IGUAL, OP_MAYOR_IGUAL, OP_DIST, OP_ASIGN, OP_ASIGN_DECLR, C_A, C_C, P_A, P_C, L_A, L_C,
	WHILE, IF, ELSE, TIPO_INT, TIPO_FLOAT, TIPO_STRING, PRINT, DECLARE, ENDDECLARE, BEGIN, END, ERROR, ERROR_COMMENT,
	ESPCHAR, COMMENT, ESPACIO, COM, MAP
}
